# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    paths:
      - '**.js'
      - '**.css'
      - '**.json'
      - '**.html'
      - '**.yml'
    branches: [ master ]
  pull_request:
    paths:
      - '**.js'
      - '**.css'
      - '**.json'
      - '**.html'
      - '**.yml'
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:  [12.x, 14.x, 15.x, 16.x]
        os: [windows-latest, ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.7'
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm config set python python2.7
      if: runner.os != 'Linux'
    - run: npm install --global --no-optional windows-build-tools --vs2015
      if: runner.os != 'Linux'
    - run: npm config set msvs_version 2015 –global
      if: runner.os != 'Linux'
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test-cov
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Codacy Coverage Reporter
      if: runner.os == 'Linux'
      uses: codacy/codacy-coverage-reporter-action@0.2.0
      with:
        project-token: ${{ secrets.CODACY_TOKEN }}
        coverage-reports: ./coverage/lcov.info
